# Use an official Node.js runtime as a parent image
FROM node:20.6.1

# Set the working directory in the container
WORKDIR /app

# Expose the port that the app will run on
EXPOSE 5173

# Define the command to run your app
CMD ["npm","run","dev","--","--host"]